Update docker-compose
Add custom volumes and netwok

diff --git a/config/judge/entrypoint b/config/judge/entrypoint
--- a/config/judge/entrypoint
+++ b/config/judge/entrypoint
@@ -13,8 +13,10 @@ run) command=(dmoj) ;;
 cli) command=(dmoj-cli) ;;
 test) command=(python3 -- -m dmoj.testsuite testsuite) ;;
 *)
-  echo "Invalid command, must be one of [run, cli, test]" 1>&2
-  exit 1
+#  echo "Invalid command, must be one of [run, cli, test]" 1>&2
+  # shellcheck disable=SC2206
+  # shellcheck disable=SC2034
+  command=(dmoj -c /judge.yml $JUDGE_SITE $JUDGE_NAME $JUDGE_KEY)
   ;;
 esac
 
@@ -26,4 +28,4 @@ echo 'problem_storage_root:
 - /problems
 ' >> /judge.yml
 
-runuser -u judge "dmoj -c /judge.yml $JUDGE_SITE $JUDGE_NAME $JUDGE_KEY"
+runuser -u judge "${command[@]}" -- "$@"
