Update docker-compose
Add custom volumes and netwok

diff --git a/config/judge/entrypoint b/config/judge/entrypoint
--- a/config/judge/entrypoint
+++ b/config/judge/entrypoint
@@ -8,10 +8,20 @@ export PYTHONIOENCODING=utf8
 cd /judge || exit
 pip3 install -q -e .
 
+case "$1" in
+run) command=(dmoj) ;;
+cli) command=(dmoj-cli) ;;
+test) command=(python3 -- -m dmoj.testsuite testsuite) ;;
+*)
+  echo "Invalid command, must be one of [run, cli, test]" 1>&2
+  exit 1
+  ;;
+esac
+
 shift
 . ~judge/.profile
 
-dmoj-autoconf > /judge.yml
+runuser -u judge "dmoj-autoconf > /judge.yml"
 echo 'problem_storage_root:
 - /problems
 ' >> /judge.yml
